# File Types in GISc Work

The scientific computing work that takes place in geographic information science requires a multitude of file types.

### Stata Files

There are a number of file types that are important for our use of Stata. These are all likely file types that you have never come across before, and are all discussed in greater detail in the Introducing Stata chapter (see page ).

  - `.do` - “Stata Do-files” - These are code files that contain
    commands that Stata can execute automatically. All final analyses and manipulations for research should be done via do-files to increase project documentation and reproducibility.

  -  `.dta` - “Stata Datasets” - These are the format that Stata stores tabular data in. We call these “D-T-A” files.

  - `.smcl` - “Stata Log-files” - The default file format for Stata log-files is the `.smcl` file format, which is a varient of `html`. It is pronounced “smick-el”. I recommend avoiding this file format whenever possible since only Stata can read it. Instead, save your log-files using the `.txt` file extension and the `text` option. The `.txt` file-type is a so-called “plain text” file format that can be read by an innumerable number of applications. This makes it excellent for reproducibility.

### Other Files
We will also use a number of other types of files throughout the
semester. Some may be file types that you have come across before.

  - `.md` - “Markdown files” - These are plain text files that contain Markdown syntax (see page ). They are saved with a special file extension so that software applications and web browsers know to take advantage of the embedded Markdown syntax.

  - `.png` - “Portable Network Graphics” or “PNG files” - These are image files designed primarily for use on the Internet and on computer displays.

  - `.txt` - “Plain text files” or “Text files” - These are files that contain text without any formatting (like bold or italicized text, for example). These can be opened by a wide array of text editor applications across all major operating systems.
